server:
  port: 9003

spring:
  application:
    name: feign-consumer-hystrix

#Feign是自带断路器的，如果在Dalston版本的Spring Cloud中，
  #它没有默认打开。需要需要在配置文件中配置打开它,本项目我们是不需要打开的
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
