spring:
  application:
    name: zuul-service
server:
  port: 9003

#zuul:
#  routes:
#    blog:
#      path: /lm/**
#      url: https://www.baidu.com
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  routes:
#    api:
#      path: /**
#      serviceId: eureka-provider