spring:
  application:
    name: zuul-service-filter

server:
  port: 9004
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api:
      path: /**
      serviceId: eureka-provider


